bbgi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from .sitemaps import StaticViewSitemap, CampaignSitemap, EventSitemap, BlogSitemap, BusinessSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'listings': BusinessSitemap,
    'campaigns': CampaignSitemap,
    'events': EventSitemap,
    'blogs': BlogSitemap
}


urlpatterns = [
    path('bbgi-admin/', admin.site.urls),
    path("", include("bbgi_home.urls", namespace="bbgi_home")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("listings.urls", namespace="listings")),
    path("", include("campaigns.urls", namespace="campaigns")),
    path("", include("events.urls", namespace="events")),
    path("", include("coupons.urls", namespace="coupons")),
    path("", include("markets.urls", namespace="markets")),
    path("", include("payments.urls", namespace="payments")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campaigns/urls.py
from django.urls import path 
from campaigns.views.campaign import (campaigns, campaign_details, create_campaign_address, add_campaign_socials, update_campaign_address, update_campaign_contact,
                                      create_campaign, update_campaign, delete_campaign, manage_campaigns, manage_campaign, generate_contributors_list)
from campaigns.views.contribution import (
    create_contribution, cancel_contribution, contribution, contributions, manage_contribution, manage_contributions
)
from campaigns.views.campaign_update import create_campaign_update, delete_campaign_update

app_name = "campaigns"
urlpatterns = [
    path("campaigns", campaigns, name="campaigns"),
    path("campaign/manage", manage_campaigns, name="manage-campaigns"),
    path("campaign/get-started", create_campaign, name="create-campaign"),
    path("campaign/get-started/<slug:campaign_slug>", create_campaign, name="create-campaign-with-slug"),
    path("campaign/add-address/<slug:campaign_slug>", create_campaign_address, name="create-campaign-address"),
    path("campaign/add-contact/<slug:campaign_slug>", add_campaign_socials, name="create-campaign-contact"),
    path("<slug:category_slug>", campaigns, name="campaign-by-category"),
    path("campaing/<slug:campaign_slug>", campaign_details, name="campaign"),
    path("campaign/manage/<uuid:campaign_id>", manage_campaign, name="manage-campaign"),
    path("campaign/update-details/<slug:campaign_slug>", update_campaign, name="update-campaign"),
    path("campaign/update-address/<slug:campaign_slug>", update_campaign_address, name="update-campaign-address"),
    path("campaign/update-contact/<slug:campaign_slug>", update_campaign_contact, name="update-campaign-contact"),
    path("campaign/delete/<slug:campaign_slug>", delete_campaign, name="delete-campaign"),

    path("campaign/updates/create/<slug:campaign_slug>", create_campaign_update, name="create-campaign-update"),
    path("campaign/updates/delete/<uuid:update_id>", delete_campaign_update, name="delete-campaign-update"),

    path("contributions/all", contributions, name="all-contributions"),
    path("contribution/all/<uuid:campaign_id>", contributions, name="contributions"),
    path("contribution/manage", manage_contributions, name="manage-contributions"),
    path("contribution/<uuid:campaign_id>/<uuid:contribution_id>", contribution, name="contribution"),
    path("contribution/manage/<uuid:contribution_id>", manage_contribution, name="manage-contribution"),
    path("contribution/create/<uuid:campaign_id>", create_contribution, name="create-contribution"),
    path("contribution/cancel/<uuid:contribution_id>", cancel_contribution, name="cancel-contribution"),
    path("contribution/generate/contributors/<uuid:campaign_id>", generate_contributors_list, name="generate-contributors-list")
    
]

campaigns/models.py
from datetime import timedelta
import decimal
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from accounts.custom_models.abstracts import AbstractPayment
from accounts.models import AbstractCreate
from accounts.utilities.validators import validate_fcbk_link, validate_insta_link, verify_rsa_phone, validate_in_link, validate_twitter_link
from campaigns.utils import handle_campaign_file_upload, PaymentStatus, Tip
from django.db import models
from django.utils import timezone
from accounts.custom_models.choices import StatusChoices
from bbgi_home.models import BlogCategory
from django.dispatch import receiver
from django.db.models.signals import pre_delete
from django.utils.safestring import mark_safe
from django.utils.translation import gettext as _
from django.contrib.auth import get_user_model
from tinymce.models import HTMLField

User = get_user_model()
PHONE_REGEX = verify_rsa_phone()

def in_fourteen_days():
    return timezone.now() + timedelta(days=14)

def five_days():
    return timezone.now() + timedelta(days=5)

class CampaignModel(AbstractCreate):
    image = models.ImageField(help_text=_("Upload campaign image."), upload_to=handle_campaign_file_upload, blank=True, null=True)
    title = models.CharField(help_text=_("Enter title for your campaign"), max_length=150)
    slug = models.SlugField(max_length=250, blank=True)
    organiser = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name="campaigns")
    category = models.ForeignKey(BlogCategory, on_delete=models.PROTECT, related_name="campaigns")
    small_description = models.TextField(help_text=_("Small description about your campaign for search optimization."), null=True, blank=True)
    details = HTMLField(help_text=_("Enter additional details about your campaign"))
    target = models.DecimalField(help_text=_("Enter target amount"),max_digits=1000, decimal_places=2, default=0.00)
    current_amount = models.DecimalField(max_digits=1000, decimal_places=2, default=0.00)
    phone = models.CharField(help_text=_("Enter cellphone number"), max_length=15, validators=[PHONE_REGEX], null=True, blank=True)
    alternative_phone = models.CharField(help_text=_("Enter your business number"), max_length=15, validators=[PHONE_REGEX], null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    facebook = models.URLField(validators=[validate_fcbk_link], blank=True, null=True)
    twitter = models.URLField(validators=[validate_twitter_link], blank=True, null=True)
    instagram = models.URLField(validators=[validate_insta_link], blank=True, null=True)
    linkedIn = models.URLField(validators=[validate_in_link], blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    campaign_address = models.CharField(max_length=300, help_text=_("Enter campaign address seperated by comma"), null=True, blank=True)
    map_coordinates  = models.CharField(max_length=300, blank=True, null=True)
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=in_fourteen_days, validators=[MinValueValidator(timezone.now(), "Date should not be less that today's date")])
    status = models.CharField(max_length=50, choices=StatusChoices.choices, default=StatusChoices.NOT_APPROVED)
    is_featured = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("Campaigns")
        verbose_name_plural = _("Campaigns")
        ordering = ["-created"]

    def get_absolute_url(self):
        return reverse("campaigns:campaign", kwargs={"campaign_slug": self.slug})

    def get_days(self):
        date = self.end_date - timezone.now()
        if date.days < 0:
            return "0 days"
        if date.days > 1:
            return f"{date.days} days"
        else:
            return f"{date.days} day"

    def get_percentage_of_donated_fund(self):
        val = self.current_amount / self.target
        perc = val * 100
        if perc > decimal.Decimal(100):
            return round(100, 2)
        return round(perc, 2)
    

    def __str__(self):
        return str(self.title)
    
    def image_tag(self):
        if self.image:
            return mark_safe(f"<img src={self.image.url} alt={self.title}-image height='60' width='90' />")
        return ""
    
    def thumpnail(self):
        if self.image:
            return mark_safe(f"<img src={self.image.url} alt={self.organiser.first_name}-image height='60' width='60' style='border-radius: 50%; height: 40px; width: 40px;' />")
        return ""

    def content_safe(self):
        return mark_safe(self.details)

class CampaignContent(AbstractCreate):
    image = models.ImageField(help_text=_("Upload emages images."), upload_to="campaigns/images/content/")
    campaign = models.ForeignKey(CampaignModel, on_delete=models.CASCADE, related_name="images")
    
    def __str__(self):
        return self.campaign.title + "content"
    
class CampaignReview(AbstractCreate):
    rating_value = models.IntegerField(validators=[
            MinValueValidator(0),   
            MaxValueValidator(5)  
        ])
    commenter = models.ForeignKey(get_user_model(), related_name="campaign_reviews", on_delete=models.SET_NULL, null=True)
    commenter_email = models.EmailField()
    commenter_full_names = models.CharField(max_length=300)
    campaign = models.ForeignKey(CampaignModel, on_delete=models.CASCADE, related_name="reviews")
    comment_title = models.CharField(max_length=250)
    comment = models.TextField()

    class Meta:
        verbose_name = 'Campaign Review'
        verbose_name_plural = 'Campaign Reviews'

    def __str__(self) -> str:
        return self.commenter_email
    
class CampaignUpdateModel(AbstractCreate):
    campaign = models.ForeignKey(CampaignModel, on_delete=models.CASCADE, related_name="updates")
    title = models.CharField(max_length=250)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Campaign Update'
        verbose_name_plural = 'Campaign Updates'

    def __str__(self) -> str:
        return f'Update for {self.campaign.title} - {self.created}'
    
class ContributionModel(AbstractCreate, AbstractPayment):
    order_number = models.CharField(max_length=300, editable=False, unique=True)
    checkout_id = models.CharField(max_length=200, unique=True, null=True, blank=True, db_index=True)
    amount = models.DecimalField(max_digits=1000, decimal_places=2, help_text=_("Enter contribution amount"))
    tip = models.CharField(default=Tip.TEN, max_length=25, choices=Tip.choices)
    total_amount = models.DecimalField(max_digits=1000, decimal_places=2)
    accepted_laws = models.BooleanField(default=True)
    message = models.TextField(blank=True, null=True)
    paid = models.CharField(max_length=40, choices=PaymentStatus.choices, default=PaymentStatus.NOT_PAID)
    campaign = models.ForeignKey(CampaignModel, on_delete=models.CASCADE, related_name="contributions")
    anonymous = models.BooleanField(default=False)
    contributor = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=None, null=True, related_name="contributions")
    receipt = models.FileField(null=True, upload_to="contributions/receipts/")

    class Meta:
        verbose_name = _("Contribution")
        verbose_name_plural = _("Contributions")
        ordering = ["-created"]

    def calculate_tip_amount(self):
        if self.tip == "10%":
            tip_amount = decimal.Decimal(self.amount) * decimal.Decimal((10 / 100))
        elif self.tip == "15%":
            tip_amount = decimal.Decimal(self.amount) * decimal.Decimal((15 / 100))
        elif self.tip == "20%":
            tip_amount = decimal.Decimal(self.amount) * decimal.Decimal((20 / 100))
        else:
            tip_amount = decimal.Decimal(self.amount) * decimal.Decimal((25 / 100))
        return round(tip_amount, 2)

    def calculate_total(self):
        
        return decimal.Decimal(self.amount)
    
    

    def __str__(self):
        return str(self.amount)
    
    def contribution_percentage(self):
        perc = (self.amount / self.campaign.target) * 100
        return f"{round(perc, 2)}%"
    
    def get_absolute_url(self):
        return reverse("campaigns:contribution", kwargs={"campaign_id": self.campaign.id, "contribution_id": self.id})
    

    def save(self, *args, **kwargs):
        self.total_amount = round(self.calculate_total(), 2)
        super(ContributionModel, self).save(*args, **kwargs)

@receiver(pre_delete, sender=CampaignModel)
def delete_campaign_image_hook(sender, instance, using, **kwargs):
    instance.image.delete()

@receiver(pre_delete, sender=ContributionModel)
def delete_campaign_image_hook(sender, instance, using, **kwargs):
    instance.receipt.delete()

bbgi_home/views/campaigns_views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, redirect
from bbgi_home.forms import CampaignUpdateStatusForm
from bbgi_home.utilities.decorators import user_not_superuser_or_staff
from campaigns.models import CampaignModel, ContributionModel
from django.contrib import messages

from campaigns.utils import PaymentStatus

USER = get_user_model()

@login_required
@user_not_superuser_or_staff
def all_campaigns(request, username=None):
    query = request.GET.get("query", None)
    queryset = CampaignModel.objects.all()
    if username:
        user = get_object_or_404(USER, username=username)
        if query:
            campaigns = queryset.filter(Q(organiser = user) & Q(title__icontains=query)| Q(organiser__first_name__icontains=query))
        else:
            campaigns = queryset.filter(organiser = user)
    else:
        if query:
            campaigns = queryset.filter(Q(title__icontains=query)| Q(organiser__first_name__icontains=query))
        else:
            campaigns = queryset
    
    return render(request, "dashboard/campaigns/all-campaigns.html", {"campaigns": campaigns, "query": query})

@login_required
@user_not_superuser_or_staff
def campaign_details(request, campaign_slug):
    
    queryset = CampaignModel.objects.select_related("organiser", "category").prefetch_related("contributions").order_by("-created")
    campaign = get_object_or_404(queryset, slug = campaign_slug)
    backers = campaign.contributions.filter(paid="PAID").count()
    form = CampaignUpdateStatusForm(instance=campaign)

    if request.method == "POST":
        form = CampaignUpdateStatusForm(instance=campaign, data=request.POST)
        if form.is_valid():
            campaign = form.save()
            messages.success(request, "Campaign status was changed successfully")
            return redirect("bbgi_home:campaign-details", campaign_slug=campaign.slug)
    

    return render(request, "dashboard/campaigns/campaign-details.html", {"campaign": campaign, "form": form, "backers": backers})

@login_required
@user_not_superuser_or_staff
def all_contributions(request, campaign_id = None):
    
    contributions = ContributionModel.objects.select_related("contributor").all()
    campaign_model = None

    if campaign_id:
        campaign_model = get_object_or_404(CampaignModel, id=campaign_id)
        contributions = ContributionModel.objects.filter(campaign = campaign_model).select_related("contributor")
        

    return render(request, "dashboard/contributions/contributions.html", {"orders": contributions, "campaign": campaign_model})

@login_required
@user_not_superuser_or_staff
def contribution_details(request, contribution_id):
    contributions = ContributionModel.objects.all().select_related("contributor")
    contribution = get_object_or_404(contributions, id=contribution_id)
    return render(request, "dashboard/contributions/details.html", {"order": contribution})

@login_required
@user_not_superuser_or_staff
def delete_contribution(request, contribution_id):
    contribution = get_object_or_404(ContributionModel, id = contribution_id)
    if contribution.paid == PaymentStatus.PAID:
        messages.warning(request, "You cannot delete already paid payment contribution, please visit our <a href='' class='text-custom-primary'>refund policy</a>")
        return redirect("bbgi_home:all-contributions")
    
    if request.method == "POST":
        contribution.delete()
        messages.success(request, "You contribution was deleted successfully")
        return redirect("bbgi_home:all-contributions")
    
    return render(request, "campaigns/delete/confirm_delete.html", {"message": f"Are you sure you want to cancel this contribution ({contribution.order_number})?", "title": "Cancel Contribution"})

campaigns/templates/campaigns/campaign/update.html
{% extends '_update-campaign.html' %}
{% load static %}

{% block title %}Update campaign{% endblock title %}

{% block campaign %}

<div class="w-full pb-20 h-full bg-white">
    <div class="space-y-4 bg-white w-full relative">
        {% include "includes/errors.html" %}
        <div class="px-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="flex items-start flex-col gap-7">
                    <div class="bg-white w-full">
                        <h6 class="text-custom-h text-base mt-3 mb-6 font-bold uppercase">
                            Campaign Information
                        </h6>
                        <div class="flex flex-wrap">
                            <div class="w-full lg:w-12/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_image">
                                        campaign picture*
                                    </label>
                                    {{form.image}}
                                    <div class="w-full border rounded-md bg-white border-dotted p-6">
                                        <div
                                            class="flex items-center flex-col md:flex-row gap-4 w-full justify-between">
                                            <div class="flex items-center space-x-4">
                                                <div id="img_container" {% if form.image.value %}data-image="{{form.image.value.url}}"{% endif %}
                                                    class="h-16 w-20 overflow-hidden rounded bg-gray-300">
                                                    <div id="no_image"></div>
                                                </div>
                                                <div class="space-y-1">
                                                    <p class="text-xs font-bold text-gray-500">Upload image
                                                        to illustrate your campaign</p>
                                                    <p class="text-xs font-light text-gray-500">SVG, PNG,
                                                        JPG, JPEG or GIF</p>
                                                </div>
                                            </div>
                                            <div id="pick_image"
                                                class="border p-2 cursor-pointer text-center text-black">
                                                <p class="text-sm">Browser</p>
                                            </div>
                                        </div>
                                    </div>

                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.image.help_text}}</span>
                                    {% if form.image.errors %}
                                    <span
                                        class="text-[11px] text-red-500 block font-normal lowercase">{{form.image.errors.as_text}}</span>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="w-full lg:w-12/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_title">
                                        Title*
                                    </label>
                                    {{form.title}}
                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.title.help_text}}</span>

                                </div>
                            </div>
                            <div class="w-full lg:w-6/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_category">
                                        category*
                                    </label>
                                    {{form.category}}
                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.category.help_text}}</span>
                                </div>
                            </div>
                            <div class="w-full lg:w-6/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_target">
                                        target*
                                    </label>
                                    {{form.target}}
                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.target.help_text}}</span>

                                </div>
                            </div>

                            <div class="w-full lg:w-6/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_end_date">
                                        Start date*
                                    </label>
                                    {{form.start_date}}
                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.start_date.help_text}}</span>
                                </div>
                            </div>
                            <div class="w-full lg:w-6/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_end_date">
                                        End date*
                                    </label>
                                    {{form.end_date}}
                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.end_date.help_text}}</span>
                                </div>
                            </div>
                            <div class="w-full lg:w-12/12 lg:px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_small_description">
                                        Add small description about this campaign*
                                    </label>
                                    {{form.small_description}}
                            
                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.small_description.help_text}}</span>
                            
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="w-full relative">
                        <h6 class="text-custom-h text-base mt-3 mb-6 font-bold uppercase">
                            About The Campaign
                        </h6>
                        <div class="flex flex-wrap">

                            <div class="w-full px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_details">
                                        Details about the campaign*
                                    </label>

                                    {{form.details}}
                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.details.help_text}}</span>
                                    {% if form.details.errors %}
                                    <span
                                        class="text-[11px] text-red-500 block font-normal lowercase">{{form.details.errors.as_text}}</span>
                                    {% endif %}
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                
                
                <div>
                    <h5
                        class="uppercase text-sm md:text-base !text-white relative group whitespace-nowrap font-normal mb-0 transition-all duration-300 border border-custom-h hover:border-custom-primary inline-block z-0">
                        <span
                            class="inline-block absolute top-0 left-0 w-full h-full bg-custom-h group-hover:bg-custom-primary -z-1 group-hover:w-0 transition-all duration-300"></span>
                        <button type="submit"
                            class="relative z-1 px-5 font-sans md:px-[25px] lg:px-10 py-[10px] md:py-[15px] lg:py-[17px] group-hover:text-custom-h leading-1.5 uppercase">
                            Update Details
                        </button>
                    </h5>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock campaign %}
{% block js %}
<script>


    window.onload = () => {
        const file_picker = document.querySelector("#id_image"),
            pick_image = document.querySelector("#pick_image")
        const no_image = document.querySelector("#no_image");
        const img_container = document.querySelector("#img_container")
        const img = document.querySelector("#img")

        if (img_container.getAttribute("data-image")) {

            img_container.removeChild(no_image);
            img_container.innerHTML += `
                    <img
                        src="${img_container.getAttribute("data-image")}"
                        alt="{{request.user.first_name}}"
                        class="w-full h-full object-cover"
                        id="img"
                    />
                `
        }
        pick_image.addEventListener('click', () => {
            file_picker.click()
        })

        file_picker.onchange = ({target}) => {

            var file = target.files[0]
            if (file) {
                // console.log(no_image)
                if (no_image) {

                    img_container.removeChild(no_image);
                    img_container.innerHTML += `
                    <img
                        src="${window.URL.createObjectURL(file)}"
                        alt="{{request.user.first_name}}"
                        class="w-full h-full object-cover"
                        id="img"
                    />
                `
                } else {
                    img.src = window.URL.createObjectURL(file)
                }

            } else {
                alert("no file selected")
            }

        };

    }

</script>
<script>

    $(document).ready(function () {
        // Initialize DateTimePicker for startDatetime
        $('#id_start_date').datetimepicker({
            format: 'Y-m-d H:i:s',
            minDate: 0,  // Set minimum date to the current date
            step: 15,   // Set the time step to 15 minutes (optional)
        });

        // Initialize DateTimePicker for endDatetime
        $('#id_end_date').datetimepicker({
            format: 'Y-m-d H:i:s',
            minDate: 0,  // Set minimum date to the current date
            step: 15,   // Set the time step to 15 minutes (optional)
        });
    });
</script>
{% endblock js %}