bbgi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from .sitemaps import StaticViewSitemap, CampaignSitemap, EventSitemap, BlogSitemap, BusinessSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'listings': BusinessSitemap,
    'campaigns': CampaignSitemap,
    'events': EventSitemap,
    'blogs': BlogSitemap
}


urlpatterns = [
    path('bbgi-admin/', admin.site.urls),
    path("", include("bbgi_home.urls", namespace="bbgi_home")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("listings.urls", namespace="listings")),
    path("", include("campaigns.urls", namespace="campaigns")),
    path("", include("events.urls", namespace="events")),
    path("", include("coupons.urls", namespace="coupons")),
    path("", include("markets.urls", namespace="markets")),
    path("", include("payments.urls", namespace="payments")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from listings.views.business_hours import get_business_hours, update_business_hour, add_business_hours, update_business_hours
from listings.views.business_lcation import create_location, delete_location, get_locations, update_location, add_main_location, update_main_location
from listings.views.business_order import order_subscription, cancel_listing_order
from listings.views.business_views import add_listing, add_listing_socials, delete_listing, \
    delete_listing_content, get_business_hours_api, get_listing, get_listings, manage_listing, \
        manage_listings, update_listing, update_listing_content, get_started_with_listing, update_listing_socials


app_name = "listings"

urlpatterns = [
    path("businesses/", get_listings, name="listings"),
    path("account/listings/manage", manage_listings, name="manage-listings"),
    path("listings/category=<slug:category>", get_listings, name="get-listings-by-category"),
    path("business/<slug:listing_slug>", get_listing, name="get-listing"),
    path("listing/create-listing", add_listing, name = "add-listing"),
    path("listing/<slug:listing_slug>/create-listing", add_listing, name = "add-listing-with-slug"),
    path("listing/<slug:listing_slug>/create-listing-hours", add_business_hours, name = "add-business-hours"),
    path("listing/<slug:listing_slug>/add-contact-info", add_listing_socials, name = "add-business-socials"),
    path("listing/<slug:listing_slug>/add-main-location", add_main_location, name = "add-business-main-location"),
    path("listing/<slug:listing_slug>/payment-checkout", order_subscription, name = "order-subscription"),
    path("listing/<uuid:order_id>/cancel-payment-checkout", cancel_listing_order, name = "cancel-listing-order"),

    
    path("listing/get-started", get_started_with_listing, name = "get-started-with-listing"),
    path("listing/manage/delete/<slug:listing_slug>", delete_listing, name="delete-listing"),
    path("listing/manage/update/<slug:listing_slug>", update_listing, name="update-listing"),
    path("listing/manage/update-content/<slug:listing_slug>", update_listing_content, name="update-listing-content"),
    path("listing/manage/update-main-location/<slug:listing_slug>", update_main_location, name="update-main-location"),
    path("listing/manage/update-listing-socials/<slug:listing_slug>", update_listing_socials, name="update-listing-socials"),
    path("listing/manage/locations/<slug:listing_slug>", get_locations, name="get-locations"),
    path("listing/manage/add-busines-location/<slug:listing_slug>", create_location, name="create-location"),
    path("listing/manage/update-business-location/<uuid:location_id>", update_location, name="update-location"),
    path("listing/manage/delete-business-location/<uuid:location_id>", delete_location, name="delete-location"),
    path("dashboard/delete/content/<slug:listing_slug>/<uuid:content_id>", delete_listing_content, name="delete-listing-content"),
    path("listing/manage/<slug:listing_slug>", manage_listing, name="manage-listing"),
    path("listing/manage/business-hours/<slug:listing_slug>", get_business_hours, name="get-business-hours"),
    path("listing/manage/update-business-hours/<slug:listing_slug>", update_business_hours, name="update-listing-hours-big"),
    path("listing/manage/update-business-hours/<slug:listing_slug>/<uuid:hour_id>", update_business_hour, name="update-business-hour"),

    # API URLS
    path("api/hours/<uuid:listing_id>", get_business_hours_api, name="get-business-hours-api")
]

listings/models.py
from django.db import models
from django.db.models import Avg, Count
from django.urls import reverse
import decimal
from accounts.custom_models.abstracts import PHONE_VALIDATOR, AbstractPayment
from accounts.custom_models.choices import StatusChoices
from accounts.models import AbstractCreate
from django.dispatch import receiver
from django.db.models.signals import pre_delete
from django.utils.translation import gettext as _
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.core.validators import MinValueValidator, MaxValueValidator
from accounts.utilities.validators import validate_fcbk_link, validate_in_link, validate_insta_link, validate_rsa_phone, validate_twitter_link
from campaigns.utils import PaymentStatus
from listings.utilities.file_handlers import handle_business_file_upload, handle_business_verification_file_upload

DAYCHOICES = [
    ("MO", "Monday"),
    ("TU", "Tuesday"),
    ("WE", "Wednesday"),
    ("TH", "Thursday"),
    ("FR", "Friday"),
    ("SA", "Saturday"),
    ("SU", "Sunday")
    ]

BBBEE_RATINGS = [
    ("BEL1", "Level 1"),
    ("BEL2", "Level 2"),
    ("BEL3", "Level 3"),
    ("BEL4", "Level 4"),
    ("BEL5", "Level 5"),
    ("BEL6", "Level 6"),
    ("BEL7", "Level 7"),
    ("NOT", "Not sure"),
    ("NC", "Non-compliance")
    ]

HOURS_TYPE = [
    ("Open with main hours", "Open with main hours"),
    ("Open with No main hours", "Open with No main hours"),
    ("Temporary Closed", "Temporary Closed"),
    ("Permanently Closed", "Permanently Closed"),
    ("Open Online 24 hours", "Open Online 24 hours")
    ]

PROVINCES = [
    ("kzn", "KwaZulu-Natal"),
    ("mp", "Mpumalanga"),
    ("nw", "North-West"),
    ("fs", "Free-State"),
    ("wc", "Western Cape"),
    ("lp", "Limpopo"),
    ("gp", "Gauteng"),
    ("ec", "Eastern Cape"),
    ("nc", "Northern Cape"),
]

class OperatingChoices(models.TextChoices):
    CUSTOM = ("CUSTOM", "Custom")
    CLOSED = ("CLOSED", "Closed")
    OPEN = ("OPEN", "Open 24/7")

class Category(AbstractCreate):
    thumbnail = models.ImageField(upload_to="category/business/", null=True, blank=True)
    icon = models.CharField(max_length=250)
    slug = models.SlugField(max_length=350, unique=True, db_index=True)
    label = models.CharField(max_length=250, unique=True)
    

    def __str__(self):
        return str(self.label)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.label)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

class Business(AbstractCreate):
    background_image = models.ImageField(help_text=_("Upload company/business background image."), upload_to=handle_business_file_upload, blank=True, null=True)
    logo = models.ImageField(help_text=_("Upload company/business logo."), upload_to=handle_business_file_upload, blank=True, null=True)
    title = models.CharField(help_text=_("Enter title for your company/business"), max_length=150, unique=True)
    slogan = models.CharField(_("Enter your business slug"), max_length=350, null=True, blank=True)
    slug = models.SlugField(max_length=250, blank=True)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, default=None, related_name="businesses")
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="businesses")
    details = models.TextField(help_text=_("Enter additional details about your company/business"), null=True, blank=True)
    main_address = models.CharField(max_length=300, help_text=_("Enter main office address seperated by comma"), null=True, blank=True)
    map_coordinates  = models.CharField(max_length=300, blank=True, null=True)
    
    website = models.URLField(blank=True, null=True)
    email = models.EmailField(_("Enter your business email (e.g info@business.co.za)"), max_length=250, blank=True, null=True)
    bbbee_level = models.CharField(max_length=100, choices=BBBEE_RATINGS)
    province = models.CharField(max_length=300, choices=PROVINCES)
    is_hours = models.BooleanField(default=True)
    hours_type = models.CharField(max_length=250, choices=HOURS_TYPE, default=HOURS_TYPE[0][0])
    phone = models.CharField(help_text=_("Enter your business number (e.g. 021 340 9363 or +27 21 340 9363)"), max_length=15, validators=[validate_rsa_phone])
    alternative_phone = models.CharField(help_text=_("Enter your other business number (e.g. 021 340 9363 or +27 21 340 9363)"), max_length=15, validators=[validate_rsa_phone], null=True, blank=True)
    facebook = models.URLField(validators=[validate_fcbk_link], blank=True, null=True)
    twitter = models.URLField(validators=[validate_twitter_link], blank=True, null=True)
    instagram = models.URLField(validators=[validate_insta_link], blank=True, null=True)
    linkedIn = models.URLField(validators=[validate_in_link], blank=True, null=True)
    status = models.CharField(max_length=50, choices=StatusChoices.choices, default=StatusChoices.NOT_APPROVED)
    is_completed = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Business'
        verbose_name_plural = 'Businesses'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Business, self).save(*args, **kwargs)
    
    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse("listings:get-listing", kwargs={"listing_slug": self.slug})
    
    def get_full_location(self):
        return self.main_address

    def get_average_rating(self):
        reviews = self.reviews.all()
        average_rating = reviews.aggregate(Avg('rating_value'))['rating_value__avg'] or 0
        text = round(average_rating, 1)
        
        return text
    
    def get_avg_rating(self):
        return self.reviews.aggregate(avg_rating_value=Avg('rating_value'))['avg_rating_value']
        
    
    def get_location(self):
        return self.main_address

    def is_open(self):
        if self.is_hours:
            now = timezone.now()
            current_day = now.strftime('%a').upper()[:2]
            current_time = now.time()

            business_hours_today = self.business_hours.filter(day=current_day)
            for hours in business_hours_today:
                if hours.operating:
                    if hours.open_time <= current_time <= hours.close_time:
                        return True
                    else:
                        return False
                else:
                    return False
        else:
            if self.hours_type == "Temporary Closed" or self.hours_type == "Permanently Closed":
                return False
            
            return True

class BusinessContent(AbstractCreate):
    image = models.ImageField(help_text=_("Upload company/business images."), upload_to=handle_business_file_upload, blank=True, null=True)
    business = models.ForeignKey(Business, on_delete=models.CASCADE, related_name="images")

class BusinessReview(AbstractCreate):
    rating_value = models.IntegerField(validators=[
            MinValueValidator(1),   
            MaxValueValidator(5)  
        ])
    commenter = models.ForeignKey(get_user_model(), related_name="reviews", on_delete=models.SET_NULL, null=True)
    commenter_email = models.EmailField()
    commenter_full_names = models.CharField(max_length=250)
    business = models.ForeignKey(Business, on_delete=models.CASCADE, related_name="reviews")
    comment_title = models.CharField(max_length=250)
    comment = models.TextField()

    class Meta:
        verbose_name = 'Business Review'
        verbose_name_plural = 'Business Reviews'

    def __str__(self) -> str:
        return self.commenter_email

class BusinessHour(AbstractCreate):
    business = models.ForeignKey(Business, on_delete=models.CASCADE, related_name="business_hours")
    day = models.CharField(max_length=250, choices=DAYCHOICES, default=DAYCHOICES[1])
    operating = models.BooleanField(default=True)
    open_time = models.TimeField()
    close_time = models.TimeField()

    class Meta:
        unique_together = ('business', 'day')
        verbose_name = 'Business Hour'
        verbose_name_plural = 'Business Hours'

    def get_open_time(self):
        return self.open_time

    def get_close_time(self):
        return self.close_time

    def get_operating_hours(self):
        return f"{self.open_time} - {self.close_time}"

class BusinessLocation(AbstractCreate):
    business = models.ForeignKey(Business, on_delete=models.CASCADE, related_name="business_locations", null=True)
    location_title = models.CharField(max_length=350, help_text=_("Enter your business branch name"), blank=True, null=True)
    email = models.EmailField(help_text=_("Enter your business branch email"), max_length=250, blank=True, null=True)
    phone = models.CharField(help_text=_("Enter your business branch number"), max_length=15, validators=[PHONE_VALIDATOR], unique=True, null=True, blank=True)
    address = models.CharField(max_length=400, help_text=_("Enter office address seperated by comma"))
    map_coordinates  = models.CharField(max_length=300, blank=True, null=True)
    address_id = models.CharField(max_length=300, null=True, blank=True)
    
    def __str__(self):
        return self.address
    
class ListingOrder(AbstractCreate, AbstractPayment):
    listing = models.OneToOneField(Business, null=True, blank=True, on_delete=models.SET_NULL, related_name="listing_order")
    subscriber = models.ForeignKey(get_user_model(), null=True, blank=True, on_delete=models.SET_NULL, related_name="listing_orders")
    order_id = models.CharField(max_length=150, editable=False, unique=True)

    client_first_name = models.CharField(max_length=250, null=True, blank=True)
    client_last_name = models.CharField(max_length=250, null=True, blank=True)

listings/views/business_order.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from coupons.forms import CouponApplyForm
from coupons.models import Coupon
import decimal, uuid
from accounts.custom_models.choices import PaymentStatus
from listings.models import ListingOrder, Business
from accounts.utilities.company import generate_order_number
from listings.forms import ListingOrderForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q

def get_coupon(coupon_id):
    try:
        return Coupon.objects.get(id=uuid.UUID(coupon_id), active=True)
    except Coupon.DoesNotExist:
        return None
    
def apply_order_discount(order: ListingOrder, coupon: Coupon):
    order.discount = coupon.discount
    coupon.order_id = order.id
    coupon.save(update_fields=["order_id"])
    order.save(update_fields=["discount"])

@login_required
def order_subscription(request, listing_slug):
    listing = get_object_or_404(Business, slug=listing_slug, owner=request.user)
    listing_order = ListingOrder.objects.filter(listing=listing).first()
    if listing_order == None:

        listing_order= ListingOrder.objects.create(listing=listing, subscriber=request.user, order_id=generate_order_number(ListingOrder))
    

    form2 = CouponApplyForm()
    form = ListingOrderForm(instance=listing_order)
    coupon_id = request.session.get("coupon_id")
    if coupon_id:
        coupon = get_coupon(coupon_id)
        if coupon:
            apply_order_discount(listing_order, coupon)
            request.session["coupon_id"] = None

    if request.method == "POST":
        form = ListingOrderForm(instance=listing_order, data=request.POST)
        if form.is_valid():
            form.save() 
            request.session['coupon_id'] = ''
            messages.success(request, "Billing details successfully saved")
            return redirect("payments:subscription-payment", listing_order.id)
        else:
            messages.error(request, "Please fix errors below")
            
        
    return render(request, "business/order/checkout.html", {"form": form, "order": listing_order, "form2": form2})

@login_required
def cancel_listing_order(request, order_id):
    listing_order = ListingOrder.objects.filter(id=order_id).first()
    if listing_order:
        listing_order.listing.delete()
        listing_order.delete()

    messages.success(request, "Business listing successfully cancelled")
    return redirect("listings:get-started-with-listing")

listings/templates/business/hours/get-business-hours.html
{% extends '_manage-listing.html' %}
{% load static %}

{% block title %}All Business Hours{% endblock title %}

{% block content_v2 %}
<div class="relative block bg-white">
    <div class=" py-2  overflow-x-auto">
        <div class="relative flex flex-col w-full h-full text-gray-700 bg-white">
            <div class="p-6 px-0 overflow-x-auto">
                
                {% if listing.is_hours %}
                    
                
                    
                <table class="w-full text-left table-auto min-w-max">
                    <thead>
                        <tr>
                            <th class="p-4 border-y border-blue-gray-100 bg-customborder-custom-text/50">
                                <p
                                    class="block font-sans text-sm antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                                    Day
                                </p>
                            </th>




                            <th class="p-4 border-y border-blue-gray-100 bg-customborder-custom-text/50">
                                <p
                                    class="block font-sans text-sm antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                                    Operating Hours
                                </p>
                            </th>
                            <th class="p-4 border-y border-blue-gray-100 bg-customborder-custom-text/50">
                                <p
                                    class="block font-sans text-sm antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                                </p>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for hour in listing.business_hours.all %}
                        <tr>
                            <td class="p-4 border-b border-custom-text">

                                <p
                                    class="block font-sans text-sm antialiased font-normal leading-normal text-blue-gray-900">
                                    {{hour.get_day_display}}
                                </p>
                            </td>

                            {% if hour.operating %}
                            <td class="p-4 border-b border-custom-text">
                                <p class="block font-sans text-sm antialiased font-normal leading-normal text-blue-gray-900">
                                    {{hour.get_operating_hours}}
                                </p>
                            </td>
                            {% else %}
                            <td class="p-4 border-b border-custom-text">
                                <p class="block font-sans text-sm antialiased font-normal leading-normal text-blue-gray-900">
                                    closed
                                </p>
                            </td>
                            {% endif %}
                            
                            <td class="p-4 border-b border-custom-text space-x-8">
                                <a href="{% url 'listings:update-business-hour' listing_slug=listing.slug hour_id=hour.id %}"
                                    class="relative h-10 max-h-[40px] w-10 max-w-[40px] select-none rounded-lg text-center align-middle font-sans text-xs font-medium uppercase text-gray-900 transition-all hover:bg-gray-900/10 active:bg-gray-900/20 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none"
                                    type="button">
                                    <span class="">
                                        <i class="fa-solid fa-plus text-xl"></i>
                                    </span>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                    <p class="text-center mb-3 text-3xl font-semibold">Your business operation hours are currently set as <b>{{listing.hours_type}}</b></p>
                    <p class="text-center"><a href="{% url 'listings:update-listing-hours-big' listing.slug %}" class="text-xl text-primary-color text-center">Update Operating Hours</a></p>
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endblock content_v2 %}

listings/templates/business/hours/update-business-hour.html
{% extends '_business_update.html' %}
{% load static %}

{% block title %}Update Business Hour{% endblock title %}

{% block businessblock %}
<div class="relative px-4 block bg-white">
    <div class=" py-2  overflow-x-auto">
        <div class="relative flex flex-col w-full h-full text-gray-700 bg-white">
            {% include "includes/errors.html" %}
            <div class="p-6 px-0 overflow-x-auto">
                <form method="post">
                    {% csrf_token %}
                    <div class=" flex flex-wrap w-full lg:w-12/12 items-center  border border-solid justify-between gap-4 bg-white p-2">
                        <div>
                            <input id="id_day" type="text" name="day" value="{{form.day.value}}"
                                class="w-[0.1px] h-[0.1px] opacity-0 overflow-hidden absolute -z-[1]">
                            <p class="text-xl font-normal text-custom-h">{{hour.get_day_display}}</p>
                        </div>
                        <div class="space-y-1 flex gap-4 md:gap-10 items-center flex-wrap">
                            <label for="id_operating" class="inline-flex gap-4 items-center cursor-pointer">
                                <span class=" text-sm font-medium text-gray-900 dark:text-gray-300">Closed</span>
                                <input data-container="wednesday_container" type="checkbox" id="id_operating" name="operating"
                                    class="sr-only peer checkboxes" {% if hour.operating %}checked{% else %}{% endif %}>
                                <div
                                    class="relative w-11 h-6 bg-gray-200 rounded-full peer peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600">
                                </div>
                                <span class=" text-sm font-medium text-gray-900 dark:text-gray-300">Open</span>
                            </label>
                            <div id="wednesday_container" class="max-w-[16rem] grid grid-cols-2 gap-4">
                                <div>
                                    <label for="id_open_time" class="text-xs">Open time:</label>
                                    <div class="relative">
                    
                                        <input type="time" id="id_open_time" name="open_time"
                                            class="bg-gray-50 border leading-none outline-none border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2  "
                                            value="{{form.open_time.value|time:'H:i'}}" />
                                    </div>
                                </div>
                                <div>
                                    <label for="id_close_time" class="text-xs">Close time:</label>
                                    <div class="relative">
                    
                                        <input type="time" id="id_close_time" name="close_time"
                                            class="bg-gray-50 border outline-none leading-none border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2  "
                                            value="{{form.close_time.value|time:'H:i'}}" />
                                    </div>
                                </div>
                    
                            </div>
                        </div>
                    </div>
                    <div class="mt-3">
                        <div class="text-center inline-block h-12 bg-custom-primary w-[150px] rounded-md cursor-pointer">
                            <input type="submit" value="submit" class="text-white w-full h-full cursor-pointer text-sm font-semibold" />
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
{% endblock businessblock %}