accounts/urls.py
from django.urls import path
from accounts.views.company import update_company_address
from accounts.views.account_views import account_update, activate, activation_sent, add_social_links, confirm_email, custom_login, custom_logout, general, register, user_details
from accounts.views.password_views import password_change, password_reset_request, password_reset_sent, passwordResetConfirm
from accounts.views.subscribe_views import cancel_subscription_order, choose_package, subscribe, subscription_checkout
app_name = "accounts"
urlpatterns = [
    path("login", custom_login, name="login"),
    path('logout', custom_logout, name='logout'),
    path("register", register, name="register"),
    path('details/<str:username>', user_details, name="user-details"),
    path('register/success', activation_sent, name='success'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('confirm/email/<uidb64>/<token>', confirm_email, name='confirm-email'),
    path("password/reset", password_reset_request, name="password-reset"),
    path('password/success', password_reset_sent, name='password-reset-sent'),
    path('password/reset/<uidb64>/<token>', passwordResetConfirm, name='password-reset-confirm'),
    path("password/reset", password_reset_request, name="password-reset"),
    path('password/success', password_reset_sent, name='password-reset-sent'),
    path('password/reset/<uidb64>/<token>', passwordResetConfirm, name='password-reset-confirm'),

    path('dashboard/update/profile', account_update, name="profile-update"),
    path('dashboard/update/contact', general, name="contact-update"),
    path('dashboard/update/password', password_change, name="password-update"),
    path('dashboard/update/social', add_social_links, name="update-social-links"),

    path('dashboard/update/company-details', update_company_address, name="update-company-details"),
    path('subscribe', choose_package, name="choose-package"),
    path('subscribe/<uuid:package_id>', subscribe, name="subscribe"),
    path('subscribe/checkout/<uuid:order_id>', subscription_checkout, name="subscription-checkout"),
    path('subscribe/cancel/<uuid:subscription_order_id>', cancel_subscription_order, name="cancel-subscription-order")
]

bbgi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from .sitemaps import StaticViewSitemap, CampaignSitemap, EventSitemap, BlogSitemap, BusinessSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'listings': BusinessSitemap,
    'campaigns': CampaignSitemap,
    'events': EventSitemap,
    'blogs': BlogSitemap
}


urlpatterns = [
    path('bbgi-admin/', admin.site.urls),
    path("", include("bbgi_home.urls", namespace="bbgi_home")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("listings.urls", namespace="listings")),
    path("", include("campaigns.urls", namespace="campaigns")),
    path("", include("events.urls", namespace="events")),
    path("", include("coupons.urls", namespace="coupons")),
    path("", include("markets.urls", namespace="markets")),
    path("", include("payments.urls", namespace="payments")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbgi_home/urls.py
from bbgi_home.views.admin_views import all_accounts, all_listings, delete_listing
from bbgi_home.views.blog_views import all_blogs, blog_details, blogs, create_blog, delete_blog, update_blog
from bbgi_home.views.campaigns_views import all_campaigns, all_contributions, campaign_details, contribution_details, delete_contribution
from bbgi_home.views.events_views import all_events, all_ticket_orders, delete_ticket_order, event_details, ticket_order_details
from bbgi_home.views.home_views import bbgi_home, about_bbgi, contact, dashboard, search, terms_and_conditions, faqs
from django.urls import path

from bbgi_home.views.markets_views import all_quotations
from bbgi_home.views.member_views import create_member, team_members, delete_member, update_member, team_member_details

app_name = 'bbgi_home'
urlpatterns = [
    path("", bbgi_home, name="bbgi-home"),
    path("about-us", about_bbgi, name="about-bbgi"),
    path("about-us/teams/<member_id>", team_member_details, name="team-member"),
    path("contact-us", contact, name="contact"),
    path("dashboard", dashboard, name="dashboard"),
    path("search", search, name="search"),
    path("bbgi/faqs", faqs, name="faqs"),
    path("privacy", terms_and_conditions, name="terms"),
    path("privacy/<slug:terms_slug>", terms_and_conditions, name="privacy"),
    path("blogs", blogs, name="blogs"),
    path("blogs/<slug:category_slug>", blogs, name="blogs-by-category"),
    path("dashboard/accounts", all_accounts, name="all-accounts"),
    path("dashboard/listings", all_listings, name="all-listings"),
    path("dashboard/listings/delete/<uuid:listing_id>", delete_listing, name="delete-listing"),
    path("dashboard/blogs", all_blogs, name="all-blogs"),
    path("dashboard/blogs/create", create_blog, name="create-blog"),
    path("blogs/details/<slug:post_slug>", blog_details, name="details-blog"),
    path("dashboard/blogs/update/<slug:post_slug>", update_blog, name="update-blog"),
    path("dashboard/blogs/delete/<slug:post_slug>", delete_blog, name="delete-blog"),

    path("dashboard/members", team_members, name="team-members"),
    path("dashboard/member/create", create_member, name="create-member"),
    path("dashboard/member/update/<member_id>", update_member, name="update-member"),
    path("dashboard/member/delete/<member_id>", delete_member, name="delete-member"),
    path("dashboard/campaigns", all_campaigns, name="all-campaigns"),
    path("dashboard/campaign/<slug:campaign_slug>", campaign_details, name="campaign-details"),
    path("dashboard/accounts/campaigns/<username>", all_campaigns, name="all-campaigns-by-username"),
    path("dashboard/events", all_events, name="all-events"),
    path("dashboard/event/<slug:event_slug>", event_details, name="event-details"),
    path("dashboard/accounts/events/<username>", all_events, name="all-events-by-username"),
    path("dashboard/contributions", all_contributions, name="all-contributions"),
    path("dashboard/contributions/<contribution_id>", contribution_details, name="contribution"),
    path("dashboard/contribution/delete/<uuid:contribution_id>", delete_contribution, name="delete-contribution"),
    path("dashboard/ticket-orders", all_ticket_orders, name="all-ticket-orders"),
    path("dashboard/ticket-orders/<order_id>", ticket_order_details, name="order"),
    path("dashboard/ticket-orders/delete/<uuid:order_id>", delete_ticket_order, name="cancel-ticket-order"),

    path("dashboard/quotations/manage", all_quotations, name="all-quotations"),
]

accounts/models.py
from accounts.custom_models.account import *

events/models.py
import uuid
from decimal import Decimal
from accounts.custom_models.choices import StatusChoices
from accounts.models import AbstractCreate
from accounts.utilities.validators import verify_rsa_phone
from accounts.custom_models.abstracts import AbstractPayment
from campaigns.utils import generate_order_number, PaymentStatus
from bbgi_home.models import BlogCategory
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models import Avg
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import pre_delete, post_save
from django.utils.translation import gettext as _
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.urls import reverse
from tinymce.models import HTMLField
from datetime import timedelta
from django.utils.safestring import mark_safe

PHONE_REGEX = verify_rsa_phone()

def handle_event_file_upload(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid.uuid4().hex, ext)
    return f"event/{filename}"

def reservation_time():
    return timezone.now() + timedelta(minutes=25)


class EventModel(AbstractCreate):
    category = models.ForeignKey(BlogCategory, on_delete=models.PROTECT, related_name="events", null=True, blank=True)
    image = models.ImageField(help_text=_("Upload campaign image."), upload_to=handle_event_file_upload, null=True, blank=True)
    title = models.CharField(help_text=_("Enter title for your event"), max_length=150)
    slug = models.SlugField(max_length=250, blank=True, unique=True)
    phone = models.CharField(help_text=_("Enter cellphone number"), max_length=15, validators=[PHONE_REGEX])
    email = models.EmailField()
    organiser = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, default=None, related_name="events")
    small_description = models.TextField(help_text=_("Small description about your event for search"), null=True, blank=True)
    content = HTMLField()
    venue_name = models.CharField(max_length=400, help_text=_("Enter event venue name"), null=True, blank=True)
    event_address = models.CharField(max_length=300, help_text=_("Enter event address seperated by comma"), null=True, blank=True)
    map_coordinates  = models.CharField(max_length=300, blank=True, null=True)
    total_seats_sold = models.PositiveIntegerField(default=0)
    event_link = models.URLField(blank=True, null=True)
    event_startdate = models.DateTimeField(validators = [MinValueValidator(timezone.now(), "Event start date and time cannot be in the past")])
    event_enddate = models.DateTimeField(validators = [MinValueValidator(timezone.now(), "Event end date and time cannot be in the past")])
    status = models.CharField(max_length=50, choices=StatusChoices.choices, default=StatusChoices.NOT_APPROVED)


    class Meta:
        verbose_name = 'Event'
        verbose_name_plural = 'Events'
        ordering = ['-created']

    def date_time_formatter(self):
        start_local = timezone.localtime(self.event_startdate)
        end_local = timezone.localtime(self.event_enddate)
        if start_local.date() == end_local.date():
            return f"{start_local.strftime('%a %d %b %Y')}, {start_local.strftime('%H:%M')} - {end_local.strftime('%H:%M')}"
        else:
            return f"{start_local.strftime('%a %d %b %Y, %H:%M')} - {end_local.strftime('%a %d %b %Y, %H:%M')}"
        
    def sales_days_left(self):
        date = self.event_enddate - timezone.now()
        if date.days < 0:
            return "0 days"
        if date.days > 1:
            return f"{date.days} days"
        else:
            return f"{date.days} day"

    def get_total_seats(self):
        total_seats = sum([ticket.available_seats for ticket in self.tickettypes.all()])
        return total_seats

    def __str__(self) -> str:
        return f"{self.title}"
    
    def get_average_rating(self):
        reviews = self.reviews.all()
        average_rating = reviews.aggregate(Avg('rating_value'))['rating_value__avg'] or 0
        text = round(average_rating, 1)
        
        return text
    
    def get_avg_rating(self):
        return self.reviews.aggregate(avg_rating_value=Avg('rating_value'))['avg_rating_value']
    
    def image_tag(self):
        if self.image.url is not None:
            return mark_safe(f"<img src={self.image.url} alt={self.title}-image height='60' width='90' />")
        return ""

    def content_safe(self):
        return mark_safe(self.content)
    
    def get_absolute_url(self):
        return reverse("events:event-details", kwargs={"event_slug": self.slug})

    def request_payout_details(self):
        if self.status == StatusChoices.COMPLETED:
            pass

class EventContent(AbstractCreate):
    image = models.ImageField(help_text=_("Upload emages images."), upload_to=handle_event_file_upload)
    event = models.ForeignKey(EventModel, on_delete=models.CASCADE, related_name="images")
    some_field = models.CharField(max_length=20, blank=True, null=True)

class EventReview(AbstractCreate):
    rating_value = models.IntegerField(validators=[
            MinValueValidator(0),   
            MaxValueValidator(5)  
        ])
    commenter = models.ForeignKey(get_user_model(), related_name="event_reviews", on_delete=models.SET_NULL, null=True)
    commenter_email = models.EmailField()
    commenter_full_names = models.CharField(max_length=300)
    event = models.ForeignKey(EventModel, on_delete=models.CASCADE, related_name="reviews")
    comment_title = models.CharField(max_length=300)
    comment = models.TextField()

    class Meta:
        verbose_name = 'Ecent Review'
        verbose_name_plural = 'Ecent Reviews'

    def __str__(self) -> str:
        return self.commenter_email

class EventOrganisor(AbstractCreate):
    event = models.ForeignKey(EventModel, on_delete=models.CASCADE, related_name="organisors")
    full_name = models.CharField(max_length=350)
    organisor_phone_one = models.CharField(max_length=15, validators=[PHONE_REGEX], unique=True, null=True, blank=True)
    organisor_email = models.EmailField(max_length=254)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Event Organisor'
        verbose_name_plural = 'Event Organisors'
        unique_together = ['full_name', 'organisor_phone_one', 'organisor_email']

class EventTicketTypeModel(AbstractCreate):
    title = models.CharField(max_length=250, help_text=_("Enter ticket type"))
    available_seats = models.PositiveIntegerField(default=0)
    sale_start = models.DateTimeField(null=True, blank=True, validators = [MinValueValidator(timezone.now(), "Ticket sale start date and time cannot be in the past")])
    sale_end = models.DateTimeField(null=True, blank=True, validators = [MinValueValidator(timezone.now(), "Ticket sale end date and time cannot be in the past")])
    price = models.DecimalField(max_digits=1000, decimal_places=2, default=0.00)
    transaction_cost = models.DecimalField(max_digits=1000, decimal_places=2, default=0.00)
    total_price = models.DecimalField(max_digits=1000, decimal_places=2, default=0.00)
    
    event = models.ForeignKey(EventModel, related_name="tickettypes", on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Event Ticket Type'
        verbose_name_plural = 'Event Ticket Types'

    def __str__(self) -> str:
        return f"{self.title} - R{self.price}"
    
    def sales_days_left(self):
        date = self.sale_end - timezone.now()
        if date.days < 0:
            return "0 days"
        if date.days > 1:
            return f"{date.days} days"
        else:
            return f"{date.days} day"
    
    def calculate_transaction_cost(self):
        cost = Decimal(self.price)
        return Decimal(round(cost, 2))
    
    def save(self, *args, **kwargs):
        self.total_price = self.calculate_transaction_cost()
        super(EventTicketTypeModel, self).save(*args, **kwargs)

class TicketOrderModel(AbstractCreate, AbstractPayment):
    order_number = models.CharField(max_length=300, editable=False, unique=True)
    checkout_id = models.CharField(max_length=200, unique=True, null=True, blank=True, db_index=True)

    client_first_name = models.CharField(max_length=250, null=True, blank=True)
    client_last_name = models.CharField(max_length=250, null=True, blank=True)
    client_phone = models.CharField(max_length=15, validators=[PHONE_REGEX], null=True, blank=True)
    client_email = models.EmailField(null=True, blank=True)

    client_address_one = models.CharField(max_length=300, blank=True, null=True)
    client_address_two = models.CharField(max_length=300, blank=True, null=True)
    client_city = models.CharField(max_length=300, blank=True, null=True)
    client_province = models.CharField(max_length=300, blank=True, null=True)
    client_country = models.CharField(max_length=300, default="South Africa")
    client_zipcode = models.BigIntegerField(blank=True, null=True)

    email = models.EmailField()
    coupon_code = models.CharField(max_length=300, null=True, blank=True)
    quantity = models.PositiveBigIntegerField(default=1)
    subtotal = models.DecimalField(max_digits=1000, decimal_places=2, default=0.00)
    order_note = models.TextField(null=True, blank=True)
    total_price = models.DecimalField(max_digits=1000, decimal_places=2)
    total_transaction_costs = models.DecimalField(max_digits=1000, decimal_places=2, default=0.00)
    discount = models.DecimalField(max_digits=1000, decimal_places=2, default=0.00)
    tip = models.DecimalField(max_digits=1000, decimal_places=2, default=0.00)
    accepted_laws = models.BooleanField(null=False, default=True)
    buyer = models.ForeignKey(get_user_model(), related_name="ticketorders", null=True, blank=True, on_delete=models.SET_NULL)
    event = models.ForeignKey(EventModel, related_name="ticket_orders", on_delete=models.CASCADE)

accounts/templates/accounts/activation_sent.html
{% extends '_base.html' %}
{% load static %}

{% block content %}
<section class="w-full font-sans mb-20">

    <div class="container">
        <div class="max-w-xl mx-auto px-4 py-10">
            <div>
                <div class="bg-white rounded-lg p-10 flex items-center shadow justify-between">
                    <div class="text-center space-y-4">
                        <div>
                            <i class="fa-solid fa-heart-circle-check text-6xl"></i>
                        </div>
                        <h2 class="text-2xl mb-4 text-custom-h text-center font-bold">Registration Success</h2>

                        <div class="text-custom-text mb-8">
                            To activate your BBGI account, we first need to verify your email address. Check your inbox. If you haven't received
                            it, please check your spam folder.
                        </div>
                        <div class="text-custom-text mb-8">
                            If you haven't receive an email, wait for 30 minutes and try to login to resend the activation link. You have 24hours to activate your account before it gets deleted.
                        </div>
                        <div>
                            <a href="{% url 'accounts:login' %}">
                                <h5
                                    class="uppercase text-sm md:text-base text-white relative group whitespace-nowrap font-normal mb-0 transition-all duration-300 border border-custom-primary hover:border-custom-h inline-block z-0">
                                    <span
                                        class="inline-block absolute top-0 right-0 w-full h-full bg-custom-primary group-hover:bg-black -z-1 group-hover:w-0 transition-all duration-300"></span>
                                    <div
                                        class="relative z-1 px-[30px] lg:px-10 py-3 md:py-[15px] lg:py-[17px] group-hover:text-custom-h leading-1.5 uppercase">
                                        <p>Log in</p>
                                    </div>
                                </h5>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends '_base.html' %}
{% load static %}
{% block styles %}
  <style>
    #bggg-loging {
        background-image: url("{% static 'imgs/home_2.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
    }
    #hero-section-bg {
        background-image: url("{% static 'imgs/home.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
        background-blend-mode: overlay;
    }
  </style>
{% endblock styles %}

{% block title %}
<title>BBGI - Account Login</title>
{% endblock title %}

{% block content %}
<section>
    <!-- banner section -->
    <div id="hero-section-"
        class="w-full bg-no-repeat bg-cover bg-center relative z-0 after:w-full after:h-full after:absolute after:top-0 after:left-0 after:bg-white after:bg-opacity-30 after:-z-1">
        <div class="container py-[110px]">
            <h1 class="text-2xl sm:text-3xl md:text-[26px] lg:text-3xl xl:text-4xl font-bold text-custom-h mb-4">
                <span class="leading-1.3 md:leading-1.3 lg:leading-1.3 xl:leading-1.3">Account</span>
            </h1>
            <ul class="breadcrumb flex gap-7 items-center text-sm lg:text-base font-bold pt-4">
                <li class="home relative leading-1.8 lg:leading-1.8">
                    <a href="{% url 'bbgi_home:bbgi-home' %}"><i class="fas fa-home text-custom-primary"></i> Home</a>
                </li>
                <li class="leading-1.8 lg:leading-1.8 text-custom-h">
                    Login
                </li>
            </ul>
        </div>
    </div>
</section>
<section>
    <div class="container pt-32 pb-[90px] lg:pb-[70px]">
        <!-- heading -->
        <div class="text-center mb-[50px]">
            <h1 class="text-2xl sm:text-3xl md:text-[26px] lg:text-3xl xl:text-[44px] font-bold text-heading-color mb-[15px]">
                <span class="leading-1.3 md:leading-1.3 lg:leading-1.3 xl:leading-1.3">Sign In <br>
                    To Your Account
                </span>
            </h1>
            <p class="text-sm lg:text-base">
                <span class="leading-1.8 lg:leading-1.8">Offering resources, networking opportunities, and educational sessions to support both career professionals and
                entrepreneurs in achieving sustainable success.</span>
            </p>
        </div>
        {% include "includes/errors.html" %}
        <div class="grid grid-cols-1 lg:grid-cols-2">
            <form method="post" class="form-primary bg-white px-[25px] md:px-[50px] pt-10 pb-[50px]">
                <!-- passwords -->
                {% csrf_token %}
                <div>
                    <div class="grid grid-cols-1 gap-[30px] pb-[30px]">
                        <!-- email -->
                        <div class="relative">
                            <input type="text" placeholder="Enter your email address*" name="username" id="id_username"
                                class="text-paragraph-color pl-5 pr-[50px] outline-none border-2 border-border-color-9 focus:border focus:border-secondary-color h-[65px] block w-full rounded-none placeholder:text-paragraph-color placeholder:text-sm placeholder:text-opacity-60">
                        </div>

                        <!-- Confirm new password -->
                        <div class="relative">
                            <input type="password" placeholder="Password*" name="password" id="id_password"
                                class="text-paragraph-color pl-5 pr-[50px] outline-none border-2 border-border-color-9 focus:border focus:border-secondary-color h-[65px] block w-full rounded-none placeholder:text-paragraph-color placeholder:text-sm placeholder:text-opacity-60 tracking-[3px]">
                        </div>
                    </div>
                </div>
                <!-- submit button -->

                <div>
                    <h5
                        class="uppercase text-sm md:text-base text-white relative group whitespace-nowrap font-normal mb-0 transition-all duration-300 border bg-secondary-color border-secondary-color hover:border-primary-color hover:bg-primary-color inline-block z-0">
                        <button type="submit"
                            class="relative z-1 px-[30px] lg:px-10 py-3 md:py-[15px] lg:py-[17px] group-hover:text-white leading-[23px] uppercase h">
                            SIGN IN
                        </button>
                    </h5>
                </div>
                <!-- forgotten password -->
                <a href="{% url 'accounts:password-reset' %}" class="uppercase mt-6 text-[13px] lg:text-sm">
                    <span class="leading-1.8 lg:leading-1.8">FORGOTTEN YOUR PASSWORD?</span>
                </a>
            </form>
            <!-- create account -->
            <div class="bg-white pt-[50px] text-center">
                <div>
                    <h5 class="text-[17px] md:text-lg lg:text-xl font-bold leading-1.3 text-heading-color mb-[15px]">
                        <span class="leading-1.3 md:leading-1.3 lg:leading-1.3">
                            DON'T HAVE AN ACCOUNT?</span>
                    </h5>
                    <p class="text-sm lg:text-base">
                        <span class="leading-1.8 lg:leading-1.8 mb-[30px]">Join us and connect with more business minded people like you</span>
                    </p>
                </div>
                <!-- submit button -->

                <div>
                    <h5
                        class="uppercase text-sm md:text-base text-white relative group whitespace-nowrap font-normal mb-0 transition-all duration-300 border bg-secondary-color border-secondary-color hover:border-primary-color hover:bg-primary-color inline-block z-0">
                        <a href="{% url 'accounts:register' %}"
                            class="relative z-1 px-5 md:px-[25px] lg:px-10 py-[10px] md:py-[15px] lg:py-[17px] group-hover:text-white leading-[23px] uppercase h">
                            CREATE ACCOUNT
                        </a>
                    </h5>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- <section class="w-full font-sans bg-custom-bg py-16 mb-20">
    <div class="container">
        <div class="">
            
            <div class="w-full">
                {% include "includes/errors.html" %}
                <div class="w-full mx-auto">
                    <form class="" method="post">
                        {% csrf_token %}
                        <div class="min-h-screen rounded-md font-sans text-gray-900 flex justify-center">
                            <div class="max-w-screen-xl m-0 sm:m-10 bg-white shadow sm:rounded-lg flex justify-center flex-1">
                                <div class="lg:w-1/2 xl:w-5/12 p-6 sm:p-12">
                                    <div>
                                        <img alt="bbgi logo" src="{% static 'imgs/logo_3.png' %}"
                                            class="w-32 mx-auto" />
                                    </div>
                                    <div class="mt-12 flex flex-col items-center">
                                        <h1 class="text-2xl xl:text-3xl font-extrabold">
                                            Sign in
                                        </h1>
                                        <div class="w-full flex-1 mt-8">
                                            
                        
                                            <div class="mx-auto max-w-xs">
                                                <input
                                                    class="w-full px-8 py-4 rounded-lg font-medium bg-gray-100 border border-gray-200 placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white"
                                                    type="text" placeholder="Email or Username" name="username" />
                                                <input
                                                    class="w-full px-8 py-4 rounded-lg font-medium bg-gray-100 border border-gray-200 placeholder-gray-500 text-sm focus:outline-none focus:border-gray-400 focus:bg-white mt-5"
                                                    type="password" placeholder="Password" name="password" />
                                                    
                                                    <p class="text-xs text-gray-600 text-right">
                                                        Forgot password?
                                                        <a href="{% url 'accounts:password-reset' %}" class="text-blue-800">
                                                            reset
                                                        </a>
                                                    </p>
                                                <button
                                                    class="mt-5 tracking-wide font-semibold bg-custom-h text-gray-100 w-full py-4 rounded-lg hover:bg-custom-h transition-all duration-300 ease-in-out flex items-center justify-center focus:shadow-outline focus:outline-none">
                                                    <svg class="w-6 h-6 -ml-2" fill="none" stroke="currentColor" stroke-width="2"
                                                        stroke-linecap="round" stroke-linejoin="round">
                                                        <path d="M16 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2" />
                                                        <circle cx="8.5" cy="7" r="4" />
                                                        <path d="M20 8v6M23 11h-6" />
                                                    </svg>
                                                    <span class="ml-3">
                                                        Sign in
                                                    </span>
                                                </button>
                                                <p class="mt-6 text-xs text-gray-600 text-center">
                                                    Do not have an account?
                                                    <a href="{% url 'accounts:register' %}" class="border-b border-gray-500 border-dotted">
                                                        Sign up
                                                    </a>
                                                    
                                                </p>
                                                <p class="mt-6 text-xs text-gray-600 text-center">
                                                    I agree to abide by BBGI's
                                                    <a href="#" class="border-b border-gray-500 border-dotted">
                                                        Terms of Service
                                                    </a>
                                                    and its
                                                    <a href="#" class="border-b border-gray-500 border-dotted">
                                                        Privacy Policy
                                                    </a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="flex-1 bg-bg-white text-center hidden lg:flex">
                                    <div id="bggg-loging" class=" w-full  bg-contain bg-center bg-no-repeat"
                                        >
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section> -->

{% endblock content %}