bbgi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from .sitemaps import StaticViewSitemap, CampaignSitemap, EventSitemap, BlogSitemap, BusinessSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'listings': BusinessSitemap,
    'campaigns': CampaignSitemap,
    'events': EventSitemap,
    'blogs': BlogSitemap
}


urlpatterns = [
    path('bbgi-admin/', admin.site.urls),
    path("", include("bbgi_home.urls", namespace="bbgi_home")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("listings.urls", namespace="listings")),
    path("", include("campaigns.urls", namespace="campaigns")),
    path("", include("events.urls", namespace="events")),
    path("", include("coupons.urls", namespace="coupons")),
    path("", include("markets.urls", namespace="markets")),
    path("", include("payments.urls", namespace="payments")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbgi_home/urls.py
from bbgi_home.views.admin_views import all_accounts, all_listings, delete_listing
from bbgi_home.views.blog_views import all_blogs, blog_details, blogs, create_blog, delete_blog, update_blog
from bbgi_home.views.campaigns_views import all_campaigns, all_contributions, campaign_details, contribution_details, delete_contribution
from bbgi_home.views.events_views import all_events, all_ticket_orders, delete_ticket_order, event_details, ticket_order_details
from bbgi_home.views.home_views import bbgi_home, about_bbgi, contact, dashboard, search, terms_and_conditions, faqs
from django.urls import path

from bbgi_home.views.markets_views import all_quotations
from bbgi_home.views.member_views import create_member, team_members, delete_member, update_member, team_member_details

app_name = 'bbgi_home'
urlpatterns = [
    path("", bbgi_home, name="bbgi-home"),
    path("about-us", about_bbgi, name="about-bbgi"),
    path("about-us/teams/<member_id>", team_member_details, name="team-member"),
    path("contact-us", contact, name="contact"),
    path("dashboard", dashboard, name="dashboard"),
    path("search", search, name="search"),
    path("bbgi/faqs", faqs, name="faqs"),
    path("privacy", terms_and_conditions, name="terms"),
    path("privacy/<slug:terms_slug>", terms_and_conditions, name="privacy"),
    path("blogs", blogs, name="blogs"),
    path("blogs/<slug:category_slug>", blogs, name="blogs-by-category"),
    path("dashboard/accounts", all_accounts, name="all-accounts"),
    path("dashboard/listings", all_listings, name="all-listings"),
    path("dashboard/listings/delete/<uuid:listing_id>", delete_listing, name="delete-listing"),
    path("dashboard/blogs", all_blogs, name="all-blogs"),
    path("dashboard/blogs/create", create_blog, name="create-blog"),
    path("blogs/details/<slug:post_slug>", blog_details, name="details-blog"),
    path("dashboard/blogs/update/<slug:post_slug>", update_blog, name="update-blog"),
    path("dashboard/blogs/delete/<slug:post_slug>", delete_blog, name="delete-blog"),

    path("dashboard/members", team_members, name="team-members"),
    path("dashboard/member/create", create_member, name="create-member"),
    path("dashboard/member/update/<member_id>", update_member, name="update-member"),
    path("dashboard/member/delete/<member_id>", delete_member, name="delete-member"),
    path("dashboard/campaigns", all_campaigns, name="all-campaigns"),
    path("dashboard/campaign/<slug:campaign_slug>", campaign_details, name="campaign-details"),
    path("dashboard/accounts/campaigns/<username>", all_campaigns, name="all-campaigns-by-username"),
    path("dashboard/events", all_events, name="all-events"),
    path("dashboard/event/<slug:event_slug>", event_details, name="event-details"),
    path("dashboard/accounts/events/<username>", all_events, name="all-events-by-username"),
    path("dashboard/contributions", all_contributions, name="all-contributions"),
    path("dashboard/contributions/<contribution_id>", contribution_details, name="contribution"),
    path("dashboard/contribution/delete/<uuid:contribution_id>", delete_contribution, name="delete-contribution"),
    path("dashboard/ticket-orders", all_ticket_orders, name="all-ticket-orders"),
    path("dashboard/ticket-orders/<order_id>", ticket_order_details, name="order"),
    path("dashboard/ticket-orders/delete/<uuid:order_id>", delete_ticket_order, name="cancel-ticket-order"),

    path("dashboard/quotations/manage", all_quotations, name="all-quotations"),
]

campaigns/urls.py
from django.urls import path 
from campaigns.views.campaign import (campaigns, campaign_details, create_campaign_address, add_campaign_socials, update_campaign_address, update_campaign_contact,
                                      create_campaign, update_campaign, delete_campaign, manage_campaigns, manage_campaign, generate_contributors_list)
from campaigns.views.contribution import (
    create_contribution, cancel_contribution, contribution, contributions, manage_contribution, manage_contributions
)
from campaigns.views.campaign_update import create_campaign_update, delete_campaign_update

app_name = "campaigns"
urlpatterns = [
    path("campaigns", campaigns, name="campaigns"),
    path("campaign/manage", manage_campaigns, name="manage-campaigns"),
    path("campaign/get-started", create_campaign, name="create-campaign"),
    path("campaign/get-started/<slug:campaign_slug>", create_campaign, name="create-campaign-with-slug"),
    path("campaign/add-address/<slug:campaign_slug>", create_campaign_address, name="create-campaign-address"),
    path("campaign/add-contact/<slug:campaign_slug>", add_campaign_socials, name="create-campaign-contact"),
    path("<slug:category_slug>", campaigns, name="campaign-by-category"),
    path("campaing/<slug:campaign_slug>", campaign_details, name="campaign"),
    path("campaign/manage/<uuid:campaign_id>", manage_campaign, name="manage-campaign"),
    path("campaign/update-details/<slug:campaign_slug>", update_campaign, name="update-campaign"),
    path("campaign/update-address/<slug:campaign_slug>", update_campaign_address, name="update-campaign-address"),
    path("campaign/update-contact/<slug:campaign_slug>", update_campaign_contact, name="update-campaign-contact"),
    path("campaign/delete/<slug:campaign_slug>", delete_campaign, name="delete-campaign"),

    path("campaign/updates/create/<slug:campaign_slug>", create_campaign_update, name="create-campaign-update"),
    path("campaign/updates/delete/<uuid:update_id>", delete_campaign_update, name="delete-campaign-update"),

    path("contributions/all", contributions, name="all-contributions"),
    path("contribution/all/<uuid:campaign_id>", contributions, name="contributions"),
    path("contribution/manage", manage_contributions, name="manage-contributions"),
    path("contribution/<uuid:campaign_id>/<uuid:contribution_id>", contribution, name="contribution"),
    path("contribution/manage/<uuid:contribution_id>", manage_contribution, name="manage-contribution"),
    path("contribution/create/<uuid:campaign_id>", create_contribution, name="create-contribution"),
    path("contribution/cancel/<uuid:contribution_id>", cancel_contribution, name="cancel-contribution"),
    path("contribution/generate/contributors/<uuid:campaign_id>", generate_contributors_list, name="generate-contributors-list")
    
]

bbgi_home/views/campaigns_views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, redirect
from bbgi_home.forms import CampaignUpdateStatusForm
from bbgi_home.utilities.decorators import user_not_superuser_or_staff
from campaigns.models import CampaignModel, ContributionModel
from django.contrib import messages

from campaigns.utils import PaymentStatus

USER = get_user_model()

@login_required
@user_not_superuser_or_staff
def all_campaigns(request, username=None):
    query = request.GET.get("query", None)
    queryset = CampaignModel.objects.all()
    if username:
        user = get_object_or_404(USER, username=username)
        if query:
            campaigns = queryset.filter(Q(organiser = user) & Q(title__icontains=query)| Q(organiser__first_name__icontains=query))
        else:
            campaigns = queryset.filter(organiser = user)
    else:
        if query:
            campaigns = queryset.filter(Q(title__icontains=query)| Q(organiser__first_name__icontains=query))
        else:
            campaigns = queryset
    
    return render(request, "dashboard/campaigns/all-campaigns.html", {"campaigns": campaigns, "query": query})

@login_required
@user_not_superuser_or_staff
def campaign_details(request, campaign_slug):
    
    queryset = CampaignModel.objects.select_related("organiser", "category").prefetch_related("contributions").order_by("-created")
    campaign = get_object_or_404(queryset, slug = campaign_slug)
    backers = campaign.contributions.filter(paid="PAID").count()
    form = CampaignUpdateStatusForm(instance=campaign)

    if request.method == "POST":
        form = CampaignUpdateStatusForm(instance=campaign, data=request.POST)
        if form.is_valid():
            campaign = form.save()
            messages.success(request, "Campaign status was changed successfully")
            return redirect("bbgi_home:campaign-details", campaign_slug=campaign.slug)
    

    return render(request, "dashboard/campaigns/campaign-details.html", {"campaign": campaign, "form": form, "backers": backers})

@login_required
@user_not_superuser_or_staff
def all_contributions(request, campaign_id = None):
    
    contributions = ContributionModel.objects.select_related("contributor").all()
    campaign_model = None

    if campaign_id:
        campaign_model = get_object_or_404(CampaignModel, id=campaign_id)
        contributions = ContributionModel.objects.filter(campaign = campaign_model).select_related("contributor")
        

    return render(request, "dashboard/contributions/contributions.html", {"orders": contributions, "campaign": campaign_model})

@login_required
@user_not_superuser_or_staff
def contribution_details(request, contribution_id):
    contributions = ContributionModel.objects.all().select_related("contributor")
    contribution = get_object_or_404(contributions, id=contribution_id)
    return render(request, "dashboard/contributions/details.html", {"order": contribution})

@login_required
@user_not_superuser_or_staff
def delete_contribution(request, contribution_id):
    contribution = get_object_or_404(ContributionModel, id = contribution_id)
    if contribution.paid == PaymentStatus.PAID:
        messages.warning(request, "You cannot delete already paid payment contribution, please visit our <a href='' class='text-custom-primary'>refund policy</a>")
        return redirect("bbgi_home:all-contributions")
    
    if request.method == "POST":
        contribution.delete()
        messages.success(request, "You contribution was deleted successfully")
        return redirect("bbgi_home:all-contributions")
    
    return render(request, "campaigns/delete/confirm_delete.html", {"message": f"Are you sure you want to cancel this contribution ({contribution.order_number})?", "title": "Cancel Contribution"})

campaigns/views/campaign_update.py
from campaigns.models import CampaignModel, CampaignUpdateModel
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from campaigns.forms import CampaignUpdateForm
from campaigns.tasks import update_2_contributors
from django.contrib.sites.shortcuts import get_current_site


@login_required
def create_campaign_update(request, campaign_slug):
    campaign = get_object_or_404(CampaignModel, slug=campaign_slug, organiser = request.user)
    if request.method == 'POST':
        form = CampaignUpdateForm(request.POST)
        if form.is_valid():
            update = form.save(commit=False)
            update.campaign = campaign
            update.save()
            messages.success(request, "Campaign update was successfully added")
            protocol = "https" if request.is_secure() else "http"
            domain = get_current_site(request).domain
            update_2_contributors.delay(update.id, domain, protocol)
            return redirect("campaigns:manage-campaign", campaign_id=campaign.id)
        else:
            messages.error(request, "Something went wrong, please fix errors below")
            return render(request, "campaigns/updates/create.html", {"form": form})
    
    return render(request, "campaigns/updates/create.html", {"form": CampaignUpdateForm()})

@login_required
def delete_campaign_update(request, update_id):
    campaign_update = get_object_or_404(CampaignUpdateModel, id = update_id)
    
    if request.method == "POST":
        campaign_update.delete()
        messages.success(request, "Campaign Update Deleted successfully!")
        return redirect("campaigns:manage-campaign", campaign_id=campaign_update.campaign.id)
    
    return render(request, "campaigns/delete/confirm_delete.html", {"message": f"Are you sure you want to delete this campaign update ({campaign_update.title})?", "title": "Delete campaign update"})

campaigns/templates/_create-campaign.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
<style>
    #f {
        color: #071a1d;
    }
</style>
{% endblock title %}
<title>BBGI - Create Campaign</title>
{% block content %}
<section>
    <!-- banner section -->
    <div
        class="w-full bg-no-repeat bg-cover bg-center relative z-0 after:w-full after:h-full after:absolute after:top-0 after:left-0 after:bg-white after:bg-opacity-30 after:-z-1">
        <div class="container py-[110px]">
            <h1 class="text-2xl sm:text-3xl md:text-[26px] lg:text-3xl xl:text-4xl font-bold text-custom-h mb-[15px]">
                <span class="leading-1.3 md:leading-1.3 lg:leading-1.3 xl:leading-1.3">Create Campaign</span>
            </h1>
            <ul class="breadcrumb flex gap-[30px] items-center text-sm lg:text-base font-bold pt-4">
                <li class="home relative leading-[1.8] lg:leading-[1.8]">
                    <a href="{% url 'bbgi_home:bbgi-home' %}" class="text-custom-h"><i
                            class="fa-solid fa-home text-custom-primary"></i> Home</a>
                </li>
                <li class="leading-[1.8] lg:leading-[1.8] text-custom-h">
                    Create Campaign
                </li>
            </ul>
        </div>
    </div>
</section>

<section>
    <div class="container py-30">
        <!-- plan tab -->
        <div class="tab plan-tab">
            <div
                class=" flex flex-wrap items-center justify-center gap-x-5 lg:gap-x-[30px] xl:gap-x-[50px] gap-y-[10px] text-sm lg:text-lg xl:text-xl text-custom-h mb-[50px]">
                <button
                    class="p-1px border-b-2 border-transparent font-semibold relative leading-1.2 after:w-[10px] after:h-[10px] after:border-[3px] after:border-white after:bg-transparent after:absolute after:bottom-0 after:left-1/2 after:-translate-x-1/2 after:translate-y-1/2 after:z-10 after:rounded-[100%] {% if request.resolver_match.url_name == 'create-campaign' or request.resolver_match.url_name == 'create-campaign-with-slug' %}active{% endif %}">
                    1. Campaign Details
                </button>

                <button
                    class="p-1px border-b-2 border-transparent font-semibold relative leading-1.2 after:w-[10px] after:h-[10px] after:border-[3px] after:border-white after:bg-transparent after:absolute after:bottom-0  after:left-1/2 after:-translate-x-1/2 after:translate-y-1/2 after:z-10 after:rounded-[100%] {% if request.resolver_match.url_name == 'create-campaign-address' %}active{% endif %}">
                    2. Campaign Address
                </button>

                <button
                    class="p-1px border-b-2 border-transparent font-semibold relative leading-1.2 after:w-[10px] after:h-[10px] after:border-[3px] after:border-white after:bg-transparent after:absolute after:bottom-0 after:left-1/2 after:-translate-x-1/2 {% if request.resolver_match.url_name == 'add-campaign-contact' %}active{% endif %} after:translate-y-1/2 after:z-10 after:rounded-[100%]">
                    3. Contact Details
                </button>
            </div>

            <div class="tab-contents">

                {% block campaign %}

                {% endblock campaign %}
            </div>
        </div>
    </div>
</section>


{% endblock content %}

campaigns/templates/_manage-campaign.html
{% extends '_base.html' %}
{% load static %}



{% block seo_tags %}
<!-- Primary Meta Tags -->
<title>BBGI - The Leading Business Growth Initiative</title>
<meta name="title" content="BBGI - The Leading Business Growth Initiative" />
<meta name="description"
    content="Black Business Growth Initiative was formed with the intention of creating a gathering of black African business owners  and professionals. It is..." />

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website" />
<meta property="og:url" content="https://bbgi.co.za/about-us" />
<meta property="og:title" content="BBGI - The Leading Business Growth Initiative" />
<meta property="og:description"
    content="Black Business Growth Initiative was formed with the intention of creating a gathering of black African business owners  and professionals. It is..." />
<meta property="og:image" content="https://bbgi.co.za{% static 'imgs/logo/logo.jpeg' %}" />

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image" />
<meta property="twitter:url" content="https://bbgi.co.za/about-us" />
<meta property="twitter:title" content="BBGI - The Leading Business Growth Initiative" />
<meta property="twitter:description"
    content="Black Business Growth Initiative was formed with the intention of creating a gathering of black African business owners  and professionals. It is..." />
<meta property="twitter:image" content="https://bbgi.co.za{% static 'imgs/logo/logo.jpeg' %}" />

<!-- Meta Tags Generated with https://metatags.io -->
{% endblock seo_tags %}

{% block styles %}
<style>
    #hero-section-bg {
        background-image: url("{% static 'imgs/home.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
        background-blend-mode: overlay;
    }
</style>
{% endblock styles %}

{% block content %}
<!-- Banner -->
<section>
    <!-- banner section -->
    <div id="hero-section-"
        class="w-full bg-no-repeat bg-cover bg-center relative z-0 after:w-full after:h-full after:absolute after:top-0 after:left-0 after:bg-white after:bg-opacity-30 after:-z-1">
        <div class="container py-[110px]">
            <h1 class="text-2xl sm:text-3xl md:text-[26px] lg:text-3xl xl:text-4xl font-bold text-custom-h mb-4">
                <span class="leading-1.3 md:leading-1.3 lg:leading-1.3 xl:leading-1.3">Campaign Management</span>
            </h1>
            <ul class="breadcrumb flex gap-7 items-center text-sm lg:text-base font-bold pt-4">
                <li class="home relative leading-1.8 lg:leading-1.8">
                    <a href="{% url 'campaigns:manage-campaigns' %}"><i class="fas fa-home text-custom-primary"></i> Manage
                        campaigns</a>
                </li>
                <li class="leading-1.8 lg:leading-1.8 text-custom-h">
                    {{campaign.title}}
                </li>
            </ul>
        </div>
    </div>
</section>
<section>
    <div class="container pb-[90px] lg:pb-32">
        <div class="tab account-tab grid grid-cols-1 lg:grid-cols-12 gap-x-[30px] gap-y-[50px]">
            <!-- sidebar navigation -->
            <div class="lg:col-start-1 lg:col-span-4">
                <ul class="tab-links lg:mr-[30px] border border-b-0 border-border-color-1">
                    <li
                        class="border-b border-border-color-1 {% if request.resolver_match.url_name == 'manage-campaign' %}active{% endif %}">
                        <a href="{% url 'campaigns:manage-campaign' campaign.id %}"
                            class="flex justify-between items-center  px-5 py-[15px] w-full text-sm lg:text-base hover:text-secondary-color transition-all duration-300 capitalize">
                            <span class="leading-1.8 lg:leading-1.8"> campaign </span>
                            <i class="fas fa-home text-sm"></i>
                        </a>
                    </li>
                    <li
                        class="border-b border-border-color-1 {% if request.resolver_match.url_name == 'contributions' %}active{% endif %}">
                        <a href="{% url 'campaigns:contributions' campaign.id %}"
                            class="flex justify-between items-center px-5 py-[15px] w-full text-sm lg:text-base hover:text-secondary-color transition-all duration-300 capitalize">
                            <span class="leading-1.8 lg:leading-1.8">Contributions</span>
                            <i class="fas fa-cart-plus text-sm"></i>
                        </a>
                    </li>
                    
                    <li
                        class="border-b border-border-color-1 {% if request.resolver_match.url_name == 'get-contributors' %}active{% endif %}">
                        <a href="{% url 'campaigns:get-contributors' campaign.id %}"
                            class="flex justify-between items-center px-5 py-[15px] w-full text-sm lg:text-base hover:text-secondary-color transition-all duration-300 capitalize">
                            <span class="leading-1.8 lg:leading-1.8"> Donors </span>
                            <i class="fas fa-user-group text-sm"></i>
                        </a>
                    </li>

                    <li class="border-b border-border-color-1">
                        <a href="{% url 'campaigns:update-campaign' campaign.slug %}"
                            class="flex justify-between items-center px-5 py-[15px] w-full text-sm lg:text-base hover:text-secondary-color transition-all duration-300 capitalize">
                            <span class="leading-1.8 lg:leading-1.8">Update Campaign </span>
                            <i class="fas fa-pen text-sm"></i>
                        </a>
                    </li>

                    <li class="border-b border-border-color-1">
                        <a href="{% url 'campaigns:delete-campaign' campaign_slug=campaign.slug %}"
                            class="flex justify-between items-center px-5 py-[15px] w-full text-sm lg:text-base hover:text-secondary-color transition-all duration-300 capitalize">
                            <span class="leading-1.8 lg:leading-1.8">Delete Campaign </span>
                            <i class="fas fa-trash text-sm"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- main content -->
            <div class="tab-contents bg-custom-bg lg:col-start-4 lg:col-span-8">
                <!-- content 1 -->
                {% block content_v2 %}

                {% endblock content_v2 %}
                <!-- content 2 -->


            </div>
        </div>
    </div>
</section>

{% endblock content %}

campaigns/templates/_update-campaign.html
{% extends '_dashboard.html' %}
{% load static %}

{% block title %}Campaign Update{% endblock title %}

{% block content %}

<div class="block relative  bg-white">
    <div class="w-full h-full">
        <div class="relative block">
            <div class="py-3 ml-4 mr-4 border-b border-b-custom-h">
                <div class="flex flex-wrap lg:items-center lg:space-x-5">
                    <div
                        class="text-custom-h w-fit text-semibold rounded-md transition-all duration-300 group   px-3 py-2 lg:px-0 lg:py-0">
                        <a href="{% url 'campaigns:update-campaign' campaign.slug %}"
                            class="py-2 px-3 duration-500 hover:bg-gray-50 rounded  font-semibold">Update Details</a>
                    </div>
                    <div class="h-full w-1 bg-gray-50"></div>
                    <div
                        class="text-custom-h w-fit text-semibold rounded-md transition-all duration-300 group  px-3 py-2 lg:px-0 lg:py-0">
                        <a href="{% url 'campaigns:update-campaign-address' campaign.slug %}"
                            class="py-2 px-3 duration-500 hover:bg-gray-50 rounded  font-semibold">Update Address</a>
                    </div>
                    <div class="h-full w-1 bg-gray-50"></div>
                    <div
                        class="text-custom-h w-fit text-semibold rounded-md transition-all duration-300 group  px-3 py-2 lg:px-0 lg:py-0">
                        <a href="{% url 'campaigns:update-campaign-contact' campaign.slug %}"
                            class="py-2 px-3 duration-500 hover:bg-gray-50 rounded  font-semibold">Update Contacts</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="relative block p-4">
            {% block campaign %}
            {% endblock campaign %}
        </div>
    </div>
</div>

{% endblock content %}